### ISSUE TITLE
Add e2e tests for API errors

### ISSUE THREAD

**Issue by gcrsaldanha** [gcrsaldanha/codeflix#2]
Currently, there is only e2e tests for happy paths.
We should add at least one non-happy path for each API.

**Comment by gcrsaldanha** [comment]
Solved by #7

**Comment by hupptechnologies** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
mehrdad-shokri, @gklo, @Imranok, @haoolii, @Randy808, @schaefbauer, @sdwuyawen, @maolivn, @epsalm, @modood, @svetoslav-mechev, @alantess, @gionatamettifogo, @namastecrypto, @abu271, @tutncrusoe, @geordee, @selimbiber, @kamal3951, @xiaopingz, @yyong1, @ozanbatuhanceylan, @bundarachada, @mperk, @greg-tbca, @vseae, @Gowtham5134, @Diversified1, @kevinalh, @tou55aint, @ecass777, @Caisin, @YunwenL, @FDani3, @Carlesgg97, @Monte9, @cnn007, @thalysmcarrara, @ph0enixd0wn420, @eightrivers, @huyhoangphan29, @zheer100, @freezy63, @stevenshelby, @0xZangetsudev, @Enochyoung, @RRLEAK, @robsoncruzs, @tgsl8r, @VenooxBalogunofAfrica, @jie17, @hritikbhandari, @ruslan2k, @slaix-cpu, @swensend, @MrishoLukamba, @soumyajitsamanta, @dunxen, @brassgum, @nrobi144, @YongseopKim, @adamschneider, @NikitaKoren, @mawenwu, @mirajshah, @SQDzhuzhuxia, @raphjaph, @Jianru-Lin, @KaetaXpog, @anhvan1999, @Ajiang-del, @chenbimo, @yueqianzhang, @kangvcar, @labetao, @psunderr, @vsanmartin, @arshrahman, @Bazinga-altf4, @taikt, @wahyudibo, @guillaumelauzier, @lobsterpub, @mozzamglori, @quocthinhvo, @stevekeol, @Hero9868, @taozle, @BlueeeMoon, @matthias-weston, @jeanmod, @lihsen, @Eurukaki, @willame, @wentijianihao, @Hrushi20, @Dendraspis, @gmgigi96, @leafrycn
